[workspace]
members = [
    "worp-client",
    "worp-core",
    "worp-dice",
    "worp-gui",
    "worp-net",
    "worp-renderer",
    "worp-scroll",
]
default-members = ["worp-client"]

[profile.release]
debug = true