[package]
name = "worp-dice"
version = "0.1.0"
authors = ["Joshua Rodgers <bytemr@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
maplit = "1.0"
logos = "0.11"
rand = { version = "0.7", features = ["wasm-bindgen"] }
paste = "1.0"
gc = { version = "0.3", features = ["derive"] }
# source-span = { version = "2.2", default-features = false }